"use strict";(self.webpackChunkjstz_docs=self.webpackChunkjstz_docs||[]).push([[890],{1539:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>c,contentTitle:()=>i,default:()=>u,frontMatter:()=>o,metadata:()=>s,toc:()=>l});const s=JSON.parse('{"id":"functions/errors","title":"Handling errors","description":"Jstz processes calls to smart functions as an atomic unit that succeeds entirely or fails entirely.","source":"@site/functions/errors.md","sourceDirName":"functions","slug":"/functions/errors","permalink":"/previews/jstz/favicon/functions/errors","draft":false,"unlisted":false,"tags":[],"version":"current","frontMatter":{"title":"Handling errors"},"sidebar":"documentationSidebar","previous":{"title":"Managing tokens","permalink":"/previews/jstz/favicon/functions/tokens"},"next":{"title":"API reference","permalink":"/previews/jstz/favicon/api/"}}');var r=t(4848),a=t(3023);const o={title:"Handling errors"},i=void 0,c={},l=[{value:"Catching errors",id:"catching-errors",level:2},{value:"Throwing exceptions",id:"throwing-exceptions",level:2}];function h(e){const n={code:"code",h2:"h2",li:"li",p:"p",pre:"pre",ul:"ul",...(0,a.R)(),...e.components};return(0,r.jsxs)(r.Fragment,{children:[(0,r.jsx)(n.p,{children:"Jstz processes calls to smart functions as an atomic unit that succeeds entirely or fails entirely.\nFailed calls to smart functions immediately revert all calls that came from that transaction and any side effects they may have had.\nFor example, assume that a user calls smart function A, which causes function A to call smart function B.\nIf smart function B throws an uncaught error, all of the calls are reverted, including the original call to function A."}),"\n",(0,r.jsx)(n.p,{children:"When a chain of calls to smart functions fails in this way, these things happen:"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:"The storage of each smart function in the chain is set back to what it was before the initial request, like a database rollback."}),"\n",(0,r.jsx)(n.li,{children:"The XTZ balance of each smart function is restored to what it was before the initial request."}),"\n",(0,r.jsx)(n.li,{children:"Any further requests generated by the smart functions are cancelled."}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"catching-errors",children:"Catching errors"}),"\n",(0,r.jsxs)(n.p,{children:["You can catch errors in smart functions just like in ordinary JavaScript/TypeScript applications, including with try/catch blocks and the ",(0,r.jsx)(n.code,{children:".catch()"})," function on promises, as in this example:"]}),"\n",(0,r.jsx)(n.pre,{children:(0,r.jsx)(n.code,{className:"language-typescript",children:'// Assume that this smart function always throws an exception\nconst alwaysFails = "KT1VzoTKPPX7ZnPrCDcj9pTUK4dTs5A9k1zv";\n\nconst handler = async (request: Request): Promise<Response> => {\n  const requester = request.headers.get("Referer") as Address;\n  console.log(`${requester} calls.`);\n\n  // Standard JavaScript try/catch\n  try {\n    await SmartFunction.call(\n      new Request(`jstz://${alwaysFails}`, {\n        method: "POST",\n        body: "",\n      }),\n    );\n  } catch (e) {\n    console.log(`Caught exception: ${e}`);\n  }\n\n  // .catch function on promise\n  await SmartFunction.call(\n    new Request(`jstz://${alwaysFails}`, {\n      method: "POST",\n      body: "",\n    }),\n  ).catch((e) => console.log(`Caught exception: ${e}`));\n\n  return new Response("OK", {\n    headers: {\n      "Content-Type": "text/utf-8",\n    },\n  });\n};\n\nexport default handler;\n'})}),"\n",(0,r.jsx)(n.p,{children:"If you call this smart function, the smart function processes the request normally, catches the errors, and returns the response to the caller."}),"\n",(0,r.jsx)(n.h2,{id:"throwing-exceptions",children:"Throwing exceptions"}),"\n",(0,r.jsxs)(n.p,{children:["Smart functions can throw exceptions in the usual ways that JavaScript/TypeScript applications throw exceptions, including by using the ",(0,r.jsx)(n.code,{children:"throw"})," keyword and by failing to catch exceptions that commands throw."]}),"\n",(0,r.jsx)(n.p,{children:"They also throw exceptions when they do things that Jstz does not allow them to do, such as sending more tez than their current balance holds or calling a smart function address that does not exist."})]})}function u(e={}){const{wrapper:n}={...(0,a.R)(),...e.components};return n?(0,r.jsx)(n,{...e,children:(0,r.jsx)(h,{...e})}):h(e)}},3023:(e,n,t)=>{t.d(n,{R:()=>o,x:()=>i});var s=t(6540);const r={},a=s.createContext(r);function o(e){const n=s.useContext(a);return s.useMemo((function(){return"function"==typeof e?e(n):{...n,...e}}),[n,e])}function i(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(r):e.components||r:o(e.components),s.createElement(a.Provider,{value:n},e.children)}}}]);